### ISSUE TITLE
Minimizing floating window causes window to become inaccessible macOS

### ISSUE THREAD

**Issue by brantwedel** [chabou/hyper-always-on-top#5]
When minimizing/hiding a "Float On Top" hyper window on macOS, restoring that hyper window causes window to hide indefinitely becoming be inaccessible.

Steps to reproduce:
1. Hide floating window on macOS
2. Attempt to restore floating window

![0zfutrjjll](https://user-images.githubusercontent.com/1801892/27519808-96f4be70-59c1-11e7-83f4-b2308843b846.gif)

Active hyper plugins:
```
config: {
  plugins: [
    'hyperterm-tab-icons',
    'hyperterm-alternatescroll',
    'hyperterm-summon',
    'hyperterm-cursor',
    'hyper-blink',
    'hyperborder',
    'hypercwd',
    'hypertitle',
    'hyperterm-title',
    'hyperterm-float',
    'hyperterm-tab-numbers',
    'hyper-always-on-top',
    'hyperterm-one-light'
  ]
}
```

Note: Just tested with the following config with same results:
```
config: {
  plugins: [
    'hyper-always-on-top'
  ]
}
```

Unchecking "Float on top" before hiding window is a workaround, so maybe a solution would be to detect when window is deactivated and deactivate floating.

**Comment by chabou** [comment]
Thank you for your documented feedback!
Maybe an electron issue but yes, we could certainly add a workaround.

**Comment by chabou** [comment]
Electron issue confirmed https://github.com/electron/electron/issues/9170

**Comment by chabou** [comment]
Will be fixed by https://github.com/electron/electron/pull/9695

**Comment by brantwedel** [comment]
I though that might be the case, I'm working on a workaround in the meantime.

**Comment by chabou** [comment]
It should have been fixed.
